(() => {
  'use strict';
  const d=document;
  if(!d||d.documentElement.dataset.spaceopsSpecialistRuntime==='1')return;
  d.documentElement.dataset.spaceopsSpecialistRuntime='1';
  const path=d.location.pathname.toLowerCase();
  const key=(path.match(/\/(ground|earth|eng)\.html$/)||[])[1]||'';
  if(!key)return;

  const base=`
    .main{position:relative;padding:14px 18px 26px!important}.top{position:relative;z-index:40;min-height:54px}.metrics{position:absolute;z-index:39;left:34px;right:34px;top:82px;margin:0!important;display:flex!important;gap:18px;border:0!important;background:transparent!important;pointer-events:none}.metric{min-height:0!important;padding:0 0 0 10px!important;border:0!important;border-left:1px solid rgba(126,183,255,.14)!important;background:transparent!important;opacity:.66}.metric:first-child{border-left:0!important;padding-left:0!important}.metric b{font-size:13px!important}.metric span{font-size:6.5px!important;letter-spacing:.09em!important}.metric em,.metric small{display:none!important}.workspace{position:relative;display:block!important;min-height:calc(100vh - 84px);margin-top:4px}.workspace>.panel:nth-child(2){position:relative;border:0!important;background:transparent!important}.workspace>.panel:nth-child(2)>.head{position:absolute;z-index:33;left:18px;bottom:18px;height:auto!important;padding:0!important;border:0!important;background:transparent!important;pointer-events:none}.workspace>.panel:nth-child(2)>.head strong{font-size:8px!important;letter-spacing:.12em;color:#d7dde4}.workspace>.panel:nth-child(2)>.head small{display:block;margin-top:3px;font-size:6.5px!important;color:#617080}.scene{height:calc(100vh - 88px)!important;min-height:650px!important;border:1px solid rgba(91,107,126,.16)!important;background:#06090e!important;box-shadow:inset 0 0 90px rgba(0,0,0,.24)!important}.sceneTools{top:92px!important;left:18px!important}.legend{border:0!important;background:rgba(7,11,16,.42)!important;backdrop-filter:blur(8px)!important}.bottom{position:relative;z-index:10;margin-top:18px!important;gap:10px!important}.bottom .panel{border-color:rgba(82,95,111,.2)!important;background:linear-gradient(180deg,rgba(16,21,28,.82),rgba(10,14,19,.82))!important}.bottom .head{height:38px!important;border-bottom-color:rgba(82,95,111,.18)!important}@media(max-width:1260px){.metrics{left:22px;right:22px;flex-wrap:wrap}.scene{height:760px!important}.bottom{grid-template-columns:1fr!important}}@media(max-width:820px){.main{padding:10px!important}.metrics{position:relative;left:auto;right:auto;top:auto;display:grid!important;grid-template-columns:repeat(2,1fr)!important;margin:10px 0!important}.workspace{min-height:auto}.scene{height:680px!important;min-height:600px!important}}
  `;
  const style=d.createElement('style');style.id='spaceops-specialist-runtime-style';

  if(key==='ground'){
    style.textContent=base+`
      .metric:nth-child(3),.metric:nth-child(4),.metric:nth-child(6){opacity:.96}.metric:nth-child(3) b,.metric:nth-child(4) b{font-size:19px!important;color:#e7edf4!important}.metric:nth-child(6) b{font-size:19px!important;color:var(--amber)!important}
      .workspace>.panel:first-child{position:absolute;z-index:37;left:18px;top:146px;width:286px;border:1px solid rgba(95,111,129,.18)!important;border-left:2px solid rgba(115,215,162,.46)!important;background:linear-gradient(180deg,rgba(8,13,19,.76),rgba(6,10,15,.48))!important;backdrop-filter:blur(14px)!important;box-shadow:0 18px 44px rgba(0,0,0,.18)!important}.workspace>.panel:first-child .head,.queuePanel .head{height:32px!important;padding:0 9px!important;border-bottom-color:rgba(85,101,119,.14)!important}.filters{padding:8px!important;gap:5px!important}.filters select,.filters input{padding:6px 7px!important;background:rgba(5,9,14,.58)!important;border-color:rgba(84,101,120,.20)!important;font-size:6.5px!important}.resourceList{max-height:390px!important}.resource{padding:7px 8px!important;border-top-color:rgba(76,91,108,.10)!important}.resourceMeta div{padding:4px!important;background:rgba(5,9,14,.46)!important;border-color:rgba(80,96,114,.14)!important}
      .queuePanel{position:absolute!important;z-index:37;right:18px;top:146px;width:320px;border:1px solid rgba(95,111,129,.18)!important;background:linear-gradient(180deg,rgba(8,13,19,.76),rgba(6,10,15,.48))!important;backdrop-filter:blur(14px)!important;box-shadow:0 18px 44px rgba(0,0,0,.18)!important}.queue{max-height:390px!important}.contact{padding:8px 9px!important;border-top-color:rgba(76,91,108,.10)!important}.contactStats div{padding:4px!important;background:rgba(5,9,14,.46)!important;border-color:rgba(80,96,114,.14)!important}.actions .mini{height:24px!important;font-size:6px!important}
      .contactBar{left:18px!important;right:18px!important;bottom:18px!important;border:1px solid rgba(86,101,119,.16)!important;background:rgba(6,10,15,.58)!important;backdrop-filter:blur(12px)!important}.timeline{position:absolute;z-index:32;left:18px;right:18px;bottom:68px;padding:8px 10px!important;border:1px solid rgba(86,101,119,.16)!important;background:rgba(6,10,15,.52)!important;backdrop-filter:blur(12px)!important}.timegrid{height:82px!important}.lane{height:20px!important}.l2{top:20px!important}.l3{top:40px!important}.l4{top:60px!important}.block{height:11px!important;top:4px!important;font-size:6px!important;padding:1px 4px!important}
      @media(max-width:1260px){.workspace>.panel:first-child{left:16px;top:160px}.queuePanel{right:16px;top:160px;width:300px}}@media(max-width:820px){.workspace>.panel:first-child,.queuePanel{position:relative!important;left:auto!important;right:auto!important;top:auto!important;width:auto!important;margin-top:10px}.timeline{left:10px!important;right:10px!important;bottom:68px!important}.contactBar{left:10px!important;right:10px!important;bottom:10px!important}}
    `;
    d.head.appendChild(style);
    const pool=d.querySelector('.workspace>.panel:first-child .head strong');if(pool)pool.textContent='GROUND RESOURCES';
    const queue=d.querySelector('.queuePanel .head strong');if(queue)queue.textContent='CONTACT QUEUE';
    d.querySelectorAll('.sceneTools .chip').forEach(b=>{b.setAttribute('aria-pressed',b.classList.contains('on')?'true':'false');b.addEventListener('click',()=>setTimeout(()=>b.setAttribute('aria-pressed',b.classList.contains('on')?'true':'false'),0));});
    ['syncBtn','reserveBtn'].forEach(id=>{const el=d.getElementById(id);if(el)el.dataset.spaceopsGroundRegression='preserved';});
    d.querySelectorAll('.contact,.resource,.block').forEach(el=>el.setAttribute('role','button'));
  }

  if(key==='earth'){
    style.textContent=base+`
      .metric:nth-child(3),.metric:nth-child(4),.metric:nth-child(5){opacity:.95}.metric:nth-child(3) b{font-size:19px!important;color:#fff!important}.metric:nth-child(4) b,.metric:nth-child(5) b{font-size:17px!important;color:#d9e3ee!important}
      .workspace>.panel:first-child{position:absolute;z-index:37;left:18px;top:146px;width:286px;border:1px solid rgba(95,111,129,.18)!important;border-left:2px solid rgba(223,63,118,.48)!important;background:linear-gradient(180deg,rgba(8,13,19,.76),rgba(6,10,15,.48))!important;backdrop-filter:blur(14px)!important;box-shadow:0 18px 44px rgba(0,0,0,.18)!important}.workspace>.panel:first-child .head,.rightPanel .head{height:32px!important;padding:0 9px!important;border-bottom-color:rgba(85,101,119,.14)!important}.tabs{border-bottom-color:rgba(82,97,114,.14)!important}.tab{height:28px!important;font-size:6.5px!important}.filters{padding:8px!important;gap:5px!important}.filters select,.filters input{padding:6px 7px!important;background:rgba(5,9,14,.58)!important;border-color:rgba(84,101,120,.20)!important;font-size:6.5px!important}.catalog{max-height:382px!important}.item{padding:7px 8px!important;border-top-color:rgba(76,91,108,.10)!important}.meta div{padding:4px!important;background:rgba(5,9,14,.46)!important;border-color:rgba(80,96,114,.14)!important}
      .rightPanel{position:absolute!important;z-index:37;right:18px;top:146px;width:318px;border:1px solid rgba(95,111,129,.18)!important;background:linear-gradient(180deg,rgba(8,13,19,.76),rgba(6,10,15,.48))!important;backdrop-filter:blur(14px)!important;box-shadow:0 18px 44px rgba(0,0,0,.18)!important}.right{max-height:392px!important}.card{padding:8px 9px!important;border-bottom-color:rgba(76,91,108,.10)!important}.card h3{font-size:8px!important}.card p{font-size:6.5px!important}.stats div{padding:4px!important;background:rgba(5,9,14,.46)!important;border-color:rgba(80,96,114,.14)!important}.mini{height:24px!important;font-size:6px!important}
      .pipeline{position:absolute!important;z-index:32;left:18px;right:18px;bottom:18px;padding:8px 10px!important;border:1px solid rgba(86,101,119,.16)!important;background:rgba(6,10,15,.58)!important;backdrop-filter:blur(12px)!important}.steps{gap:5px!important}.step{padding:6px!important;background:rgba(4,8,12,.52)!important}.step b{font-size:6.5px!important}.step small{font-size:5.7px!important}.compareOverlay{right:18px!important;top:126px!important;background:rgba(6,10,15,.72)!important;backdrop-filter:blur(12px)!important}
      @media(max-width:1260px){.workspace>.panel:first-child{left:16px;top:160px}.rightPanel{right:16px;top:160px;width:300px}}@media(max-width:820px){.workspace>.panel:first-child,.rightPanel{position:relative!important;left:auto!important;right:auto!important;top:auto!important;width:auto!important;margin-top:10px}.pipeline{left:10px!important;right:10px!important;bottom:10px!important}}
    `;
    d.head.appendChild(style);
    const left=d.querySelector('.workspace>.panel:first-child .head strong');if(left)left.textContent='SOURCE LAYERS';
    const right=d.querySelector('.rightPanel .head strong');if(right)right.textContent='SOURCE INSPECTOR';
    d.querySelectorAll('.sceneTools .chip').forEach(b=>{b.setAttribute('aria-pressed',b.classList.contains('on')?'true':'false');b.addEventListener('click',()=>setTimeout(()=>b.setAttribute('aria-pressed',b.classList.contains('on')?'true':'false'),0));});
    ['compareBtn','processBtn','fuseBtn','runBtn','saveBtn','syncBtn','productBtn'].forEach(id=>{const el=d.getElementById(id);if(el)el.dataset.spaceopsEarthRegression='preserved';});
  }

  if(key==='eng'){
    style.textContent=base+`
      .metric:first-child{opacity:1}.metric:first-child b{font-size:18px!important;color:#fff!important}.metric:nth-child(2),.metric:nth-child(3),.metric:nth-child(4){opacity:.9}.workspace>.panel:first-child{position:absolute;z-index:37;left:18px;top:146px;width:286px;border:1px solid rgba(95,111,129,.18)!important;border-left:2px solid rgba(117,217,223,.44)!important;background:linear-gradient(180deg,rgba(8,13,19,.76),rgba(6,10,15,.48))!important;backdrop-filter:blur(14px)!important;box-shadow:0 18px 44px rgba(0,0,0,.18)!important}.workspace>.panel:first-child .head,.rightPanel .head{height:32px!important;padding:0 9px!important;border-bottom-color:rgba(85,101,119,.14)!important}.assetbar{padding:8px!important}.assetbar select{padding:6px 7px!important;background:rgba(5,9,14,.58)!important;border-color:rgba(84,101,120,.20)!important;font-size:6.5px!important}.tabs{border-bottom-color:rgba(82,97,114,.14)!important}.tab{height:28px!important;font-size:6.5px!important}.stack{padding:7px!important;gap:5px!important}.engine{padding:7px!important;background:rgba(5,9,14,.48)!important;border-color:rgba(78,94,112,.14)!important}.engine.active{background:linear-gradient(90deg,rgba(117,217,223,.08),transparent 82%)!important}.meta div{padding:4px!important;background:rgba(5,9,14,.46)!important;border-color:rgba(80,96,114,.14)!important}
      .rightPanel{position:absolute!important;z-index:37;right:18px;top:146px;width:318px;border:1px solid rgba(95,111,129,.18)!important;background:linear-gradient(180deg,rgba(8,13,19,.76),rgba(6,10,15,.48))!important;backdrop-filter:blur(14px)!important;box-shadow:0 18px 44px rgba(0,0,0,.18)!important}.right{max-height:410px!important}.card{padding:8px 9px!important;border-bottom-color:rgba(76,91,108,.10)!important}.card h3{font-size:8px!important}.card p{font-size:6.5px!important}.stats div{padding:4px!important;background:rgba(5,9,14,.46)!important;border-color:rgba(80,96,114,.14)!important}.kv{padding:4px 0!important;font-size:6.5px!important}.mini{height:24px!important;font-size:6px!important}
      .hud{right:18px!important;top:92px!important;width:190px!important;border-left:1px solid rgba(117,217,223,.30)!important;border-top:0!important;border-right:0!important;border-bottom:0!important;background:linear-gradient(90deg,rgba(6,11,17,.58),rgba(6,11,17,.28))!important;backdrop-filter:blur(10px)!important}.timeline{position:absolute!important;z-index:32;left:18px;right:18px;bottom:18px;padding:8px 10px!important;border:1px solid rgba(86,101,119,.16)!important;background:rgba(6,10,15,.58)!important;backdrop-filter:blur(12px)!important}.timelineBar{height:46px!important;background:rgba(4,8,12,.52)!important}.event{top:13px!important;height:18px!important;font-size:6px!important;padding:3px 4px!important}
      @media(max-width:1260px){.workspace>.panel:first-child{left:16px;top:160px}.rightPanel{right:16px;top:160px;width:300px}}@media(max-width:820px){.workspace>.panel:first-child,.rightPanel{position:relative!important;left:auto!important;right:auto!important;top:auto!important;width:auto!important;margin-top:10px}.timeline{left:10px!important;right:10px!important;bottom:10px!important}.hud{right:10px!important;top:82px!important}}
    `;
    d.head.appendChild(style);
    const left=d.querySelector('.workspace>.panel:first-child .head strong');if(left)left.textContent='ANALYSIS ENGINES';
    const right=d.querySelector('.rightPanel .head strong');if(right)right.textContent='ENGINEERING INSPECTOR';
    d.querySelectorAll('.sceneTools .chip').forEach(b=>{b.setAttribute('aria-pressed',b.classList.contains('on')?'true':'false');b.addEventListener('click',()=>setTimeout(()=>b.setAttribute('aria-pressed',b.classList.contains('on')?'true':'false'),0));});
    ['syncBtn','caseBtn','focusAsset','runCase'].forEach(id=>{const el=d.getElementById(id);if(el)el.dataset.spaceopsEngRegression='preserved';});
    d.querySelectorAll('[data-action]').forEach(el=>el.dataset.spaceopsEngRegression='preserved');
  }
})();